### PR TITLE
Added social link validation check

### PR DESCRIPTION
**Pull request by tushar-daiya**
Fixes: #193 

Added a check when updating twitter and website link.

### CODE REVIEW

**Comment by Harsh8055** [comment]
hey, amazing , @tushar-daiya for twitter link. pleas also allow https://x.com starts with and i will merge it when that's done. thanks

**Comment by Harsh8055** [comment]
So, when i add correct twitter link but invalid website, still it sends api request. can you add a check such that if twitter link is current but not the other one, pass other link as empty. such that we don't add wrong url . 
image

**Comment by tushar-daiya** [comment]
Check added support for x dot com and fixed that issue too.

**Comment by Harsh8055** [comment]
LGTM merging

**Pull request merged**
