### PR TITLE
Sortby and View dropdown fixed

### LINKED ISSUE #178: Issue: Sort By Dropdown Remains Open When Clicking View Button
When I click on the 'View' button in the user interface, the 'Sort By' dropdown menu doesn't close automatically if it's open or vice versa. This behavior is not as expected, and I believe the dropdowns should mutually close when one of them is opened to provide a better user experience.

https://github.com/linkcollect/Main-Website-Linkcollect/assets/108505673/22bd7983-822e-4d74-91b6-4337bc719185

### PR DESCRIPTION
**Pull request by tushar-daiya**
Fixes: #178 

The issue is fixed and the dropdown are made as a single component SortActions rather than 2 different like before. Fixed the dropdown in all files. Made a custom hook for managing states so that only one dropdown remains open at a time.

https://github.com/linkcollect/Main-Website-Linkcollect/assets/108505673/454c5000-1d6f-4210-87b2-1fefe6dbf9ca

### CODE REVIEW

**Comment by Harsh8055** [comment]
Hey, thanks for the pr. We will get back on this asap

**Comment by boylerplet** [comment]
Issue is fixed, can merge

**Comment by tushar-daiya** [comment]
Anything more I have to do on this?

**Comment by subhradwip01** [comment]
LGTM

**Review by boylerplet — APPROVED** [review]

**Comment by Harsh8055** [comment]
hey @tushar-daiya can you look into https://github.com/linkcollect/Main-Website-Linkcollect/issues/149

th enoteAttached on hover is creating conflict with the dropdown of sortyby hover.

for e.g open this and hover on first https://linkcollect.io/askwhyharsh/c/647c3dac129194f5ff6deefd

also, create a co0llection and open it and click on 3 dot. same issue

**Comment by tushar-daiya** [comment]
Okay I will try to solve it.

**Comment by tushar-daiya** [comment]
@Harsh8055 I commited changes in other files which were using sort by component and its merged but now the sortby option does not work on pages other than bookmark page

**Comment by Harsh8055** [comment]
hey @tushar-daiya can you try to fix it in new pr or else we will have to look into it urgently, thanks

**Comment by Harsh8055** [comment]
let it be, i will fix it now

**Comment by tushar-daiya** [comment]
I have fixed that again. If you need I can again create a pull request for the remaining.

**Pull request merged**
