### PR TITLE
[Feat] Checking for authorization and taking action

### PR DESCRIPTION
**Pull request by Electromorphous**
Issue: Protecting-routes

### CODE REVIEW

**Comment by Harsh8055** [comment]
the deployment on vercel has failed for this dude, can you check why

**Comment by Harsh8055** [comment]
image

**Comment by Electromorphous** [comment]
Will fix it

**Comment by Electromorphous** [comment]
Check it out now

**Comment by Harsh8055** [comment]
ok, seems good but can you change the time from 5s to 3.5s, for redirecting

**Comment by Electromorphous** [comment]
Done

**Comment by Harsh8055** [comment]
seems good , merging :)

**Pull request merged**
