### PR TITLE
created a BookmarkItemV2 component inside components folder

### PR DESCRIPTION
**Pull request by Mudassirkhan2**
created a BookmarkItemV2 component inside components folder
solves Issue #50 

Desktop  view
Screenshot 2023-06-13 165623

Mobile view
Screenshot 2023-06-13 165635

### CODE REVIEW

**Comment by subhradwip01** [comment]
LGTM

**Comment by subhradwip01** [comment]
Are you working on any other issue?

**Comment by subhradwip01** [comment]
If yes please choose issues according to the raised issues.. so that I can track everything... currently all issues is assigned to everyone..I am going to create more issues...so don't worry 😄😄

**Comment by Mudassirkhan2** [comment]
> LGTM

Thank You @subhradwip01  -> Are you working on any other issue?  No

**Pull request merged**
